     services:
       - type: web
         name: streamlit-app
         env: python
         plan: free
         buildCommand: "pip install -r requirements.txt"
         startCommand: "streamlit run sample.py --server.port $PORT --server.enableCORS false"